import pandas as pd

# 🔹 Recent 2023-2024 Fake News Examples (Simulated/Representative)
recent_fake = [
    {"title": "OpenAI's Sora AI model has been used to create fake evidence in recent court case", "text": "A viral video claiming to show a high-profile crime was actually generated by Sora..."},
    {"title": "WHO announces new global pandemic treaty that will override national constitutions", "text": "The World Health Organization is secretly planning to take over global governance..."},
    {"title": "Scientists find proof that the moon is actually an artificial satellite built by aliens", "text": "New lunar samples leaked from NASA show metallic structures inside the moon..."},
    {"title": "Major bank freeze incoming: All accounts over $10k to be locked by Friday", "text": "Financial experts warn of a massive liquidity crisis and government seizure of assets..."},
    {"title": "New AI-powered brain chip allows users to download skills like in The Matrix", "text": "Elon Musk's latest Neuralink update reportedly allows instant knowledge transfer..."},
    {"title": "Viral Video: Taylor Swift endorses controversial political candidate in deepfake", "text": "The singer's likeness was used without permission to promote various agendas..."},
    {"title": "UN to implement mandatory digital IDs for all citizens by 2025", "text": "A new global resolution mandates 24/7 tracking of every human being..."},
    {"title": "Discovery of 'Ancient Internet' found in Egyptian pyramids", "text": "Archaeologists found crystal tablets capable of storing petabytes of data..."},
    {"title": "Drinking salt water every morning cures all diseases including cancer", "text": "A new study buried by Big Pharma shows that simple sea salt is the ultimate cure..."},
    {"title": "Mars Rover finds ancient 'Statue of Liberty' on the red planet", "text": "Leaked photos from Curiosity rover show a massive monument identical to New York's..."},
]

# 🔹 Recent 2023-2024 Real News Examples
recent_true = [
    {"title": "ISRO successfully launches Chandrayaan-3 landing on the moon's south pole", "text": "India becomes the first nation to achieve a soft landing near the lunar south pole..."},
    {"title": "Apple announces Vision Pro spatial computer at WWDC 2023", "text": "The new headset blends digital content with the physical world using advanced cameras..."},
    {"title": "Global temperatures hit record highs in 2023, according to NASA and NOAA", "text": "The year 2023 was officially the warmest year on record since 1880..."},
    {"title": "Microsoft integrates OpenAI's GPT-4 into Bing Search and Windows", "text": "The partnership brings generative AI capabilities to millions of users worldwide..."},
    {"title": "FIFA World Cup 2026 to be hosted across USA, Canada, and Mexico", "text": "The tournament will expand to 48 teams for the first time in history..."},
    {"title": "EU passes landmark AI Act to regulate artificial intelligence systems", "text": "The new law establishes a risk-based approach for AI development and deployment..."},
    {"title": "James Webb Telescope captures stunning images of distant nebulae and galaxies", "text": "The observatory continues to provide unprecedented views of the early universe..."},
    {"title": "US Federal Reserve holds interest rates steady as inflation cools", "text": "Central bank signals potential rate cuts later in 2024 as economic data stabilizes..."},
    {"title": "G20 Summit 2023 held in New Delhi concludes with historic joint declaration", "text": "Leaders agreed on climate goals and inclusion of African Union in the group..."},
    {"title": "Total Solar Eclipse 2024 visible across North America", "text": "Millions gathered to watch the celestial event as it crossed multiple states..."},
]

def augment_dataset(file_path, new_data):
    try:
        df = pd.read_csv(file_path)
        new_df = pd.DataFrame(new_data)
        # Add necessary columns if missing
        if 'subject' not in new_df.columns: new_df['subject'] = 'recent'
        if 'date' not in new_df.columns: new_df['date'] = '2024'
        
        combined_df = pd.concat([df, new_df], ignore_index=True)
        combined_df.to_csv(file_path, index=False)
        print(f"Successfully augmented {file_path} with {len(new_data)} samples.")
    except Exception as e:
        print(f"Error augmenting {file_path}: {e}")

if __name__ == "__main__":
    augment_dataset("fake.csv", recent_fake)
    augment_dataset("true.csv", recent_true)
